Update testing-cron.yml

diff --git a/.github/workflows/testing-cron.yml b/.github/workflows/testing-cron.yml
--- a/.github/workflows/testing-cron.yml
+++ b/.github/workflows/testing-cron.yml
@@ -19,12 +19,16 @@ jobs:
         python-version: ["3.8", "3.9", "3.10", "3.11"]
 
     steps:
-    - uses: actions/checkout@v3
+    - uses: actions/checkout@v4
     - name: Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v4
+      uses: actions/setup-python@v5
       with:
         python-version: ${{ matrix.python-version }}
 
+    - name: Install libomp for macOS
+      if: startsWith(matrix.os, 'macos')
+      run: brew install libomp
+      
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
@@ -36,8 +40,10 @@ jobs:
     - name: Test with pytest
       run: |
         coverage run --source=pyod -m pytest
-    - name: coverage report
+        
+    - name: Coverage report
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        COVERALLS_SERVICE_NAME: github-actions
       run: |
-        coveralls --service=github
+        coveralls --service=github || echo "Coveralls failed to submit - retrying..." && coveralls --service=github
